* Acronyms
- LSA :: Leaf Spring Army
- LLTLSA :: Long live the Leaf Spring Army (the Leaf Spring Army will never die)
   
* Stream Memes
- Leaf Spring Army :: The name of The Enforcer stream community. For the details
  about how the name came about, see Day 27 of the stream, from the 1 hour mark.
  You are a member of the LSA if you Like and Subscribe to the channel.
  
- The Leaf Sprint Army Sends it's Regards :: 

- Morse Code :: At the beginning of the live stream introduction, a message in
  morse code is played over a background of an air-raid siren and explosions.
  Listeners are encouraged to decode and post the answer in the live chat of the
  stream. Decoders, members of the LSA Signal Corp, are awarded with "ding ding
  ding, that’s the sound of money" during the stream.

- Day of the War in Ukraine :: The Enforcer Stream tracks the war by days since
  the Russians invaded Ukraine on the 24th February, 2022 (Day 1)

- Enjoying a Succulent Chinese Meal :: "Democracy Manifest"" Youtube Internet
  Meme of Jack Karlson (1942, 7 August 2024)

- Location Unknowns ::

- Mr. Lunchtime ::

- Turret Toss ::

- The Old Guard :: A channel member is considered a member of the Old Guard if
they have been watching the channel from the very early days of the war.

- Channel Legend ::

- Tony was driving ::

- Ruh Roh Raggy ::

- Scoobiedoo Van ::

- Sliders ::

- Alan the Marmot! :: Alan! Alan! Alan! Hello. Would you like a plum? (Day 674
  2h24m18s)

- Awwee Man! (Hotdog Man) :: (Enough said, if you don’t know, ask in the live stream chat.)

- eeGGooRR (Igor) ::

- 2 Group 2 Group ::

- Mr Lunch Time ::

- Don ::

- Vlad, Tha FAILBOAT Captin!! ::

- FPV(Drone) :: First Person View drone, where the pilot flies the drone while
  wearing goggles and viewing the flight of the drone through a front facing
  camera.

- Blayt :: As reported by the FPV Drone footage (yes, we have video evidence),
  this is commonly the last thing a Russian soldier says on the front line
  before being added to the statistics

- Snake Island :: Early in the war (Day 1) the Russians went to take Snake
  Island in the Black See. The response by the Ukrainian soldiers stationed on
  the island was “Russian warship, go fuck yourself!”. This defiant action was
  later made into a postal stamp by Ukrposhta (the Ukrainian Postal Service).

- The Moskva :: The first of Russia’s new Black Sea submarine fleet.

- The Ukraine Tractor Corp :: During the early stages of the war, Ukrainian
  farmers were observed removing disabled Russian tanks from the battle field
  with their tractors.

- Buy a Car :: Also known as “Buy that car”, “Buy Matt a Car”, “Buy tractor..”
  and "Bayraktar"". This is the name of a song used in the stream introduction
  that has also been called the theme song on the Cult of Matt.

- Cult of Matt :: This usually refers to comments in live chat of the YouTube
  stream where the Cult of Matt is seen as a replacement to religious and
  political discussion which has been banned in the channel. @EnforcerMatt
  religiously bans bots and trolls in the live chat that break these rules.

- Bobcat :: Another name for special vehiclesin the Russian loss statistics.
  They are a favorate of Enforcer Matt and a stream highlight.

- Search for Captain Crack Sparrow :: The channel name for the US
  military operation targeting Venezuela in 2025.
  
- LSA World News (was UWD, Ukrainian War Discussion) ::  Discord server
  supporting the LSA Community.
